version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "0.15.3"
    #TF_COMMAND: "apply"
    #TF_COMMAND: "destroy"
  parameter-store:
    AWS_ACCESS_KEY_ID: "access_key_id"
    AWS_SECRET_ACCESS_KEY: "secret_key"

phases:
  install:
    runtime-versions:
      python: 3.7
    on-failure: ABORT       
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
  pre_build:
    on-failure: ABORT     
    commands:
      - echo terraform execution started on `date`            
  build:
    on-failure: ABORT   
    commands:
    ## Project-1: AWS VPC, ASG, ALB, Route53, ACM, Security Groups and SNS 
      - cd "$CODEBUILD_SRC_DIR/terraform-manifest"
      - ls -lrt "$CODEBUILD_SRC_DIR/terraform-manifest"
      - terraform --version
      - terraform init 
      - terraform plan          
      - terraform apply -auto-approve
  post_build:
    on-failure: CONTINUE   
    commands:
      - echo terraform execution completed on `date`    
